package test;

public class TestQuery {

	public final static String SELECT_POST_BY_CATEGORY_PAGE = "SELECT * FROM " +
	"(SELECT ROWNUM AS NO, t.* FROM " + 
	"(SELECT * FROM " + 
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + 
	"(SELECT t1.*, t2.HIT FROM " + 
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + 
	"(SELECT * FROM " + 
	"(SELECT *  FROM (SELECT * FROM POST_TABLE WHERE CATEGORY = ?), " + 
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE WHERE CATEGORY = ?)) t1, " + 
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + 
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " + 
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " + 
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " + 
	"ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC, POST_ID DESC) t) " + 
	"WHERE NO >= ? AND NO <= ?"; 
	                             
	public final static String SELECT_POST_BY_VIEWCNT_PAGE = "SELECT * FROM " + 
	"(SELECT ROWNUM AS NO, t.* FROM " + 
	"(SELECT * FROM " + 
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + 
	"(SELECT t1.*, t2.HIT FROM " + 
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + 
	"(SELECT * FROM " + 
	"(SELECT *  FROM (SELECT * FROM POST_TABLE), " + 
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, " + 
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + 
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " + 
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " + 
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " + 
	"ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC, POST_ID DESC) t) " + 
	"WHERE NO >= ? AND NO <= ?"; 
	 
	public final static String SELECT_POST_BY_EMAPTHIZE_PAGE = "SELECT * FROM " + 
	"(SELECT ROWNUM AS NO, t.* FROM " + 
	"(SELECT * FROM " + 
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + 
	"(SELECT t1.*, t2.HIT FROM " + 
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + 
	"(SELECT * FROM " + 
	"(SELECT *  FROM (SELECT * FROM POST_TABLE), " + 
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, " + 
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + 
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " + 
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " + 
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " + 
	"ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC, POST_ID DESC) t) " + 
	"WHERE NO >= ? AND NO <= ?"; 	

	public final static String SELECT_POST_BY_CATEGORY_ALL ="SELECT * FROM " + 
	"(SELECT * FROM " + 
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + 
	"(SELECT t1.*, t2.HIT FROM " + 
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + 
	"(SELECT * FROM " + 
	"(SELECT *  FROM (SELECT * FROM POST_TABLE WHERE CATEGORY = ?), " + 
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE WHERE CATEGORY = ?)) t1, " + 
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + 
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " + 
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " + 
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " + 
	"ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC, POST_ID DESC)";   

	public final static String SELECT_POST_BY_VIEWCNT_ALL = "SELECT * FROM " +
	"(SELECT * FROM " +
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " +
	"(SELECT t1.*, t2.HIT FROM " +
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " +
	"(SELECT * FROM " +
	"(SELECT *  FROM (SELECT * FROM POST_TABLE), " +
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, " +
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " +
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " +
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " +
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " +
	"ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC, POST_ID DESC)";
    
	public final static String SELECT_POST_BY_EMPATHIZE_ALL = "SELECT * FROM " +
	"(SELECT * FROM " +
	"(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " +
	"(SELECT t1.*, t2.HIT FROM " +
	"(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " +
	"(SELECT * FROM " +
	"(SELECT *  FROM (SELECT * FROM POST_TABLE), " +
	"(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, " +
	"MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " +
	"FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, " +
	"(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 " +
	"WHERE t1.POST_ID = t2.POST_ID(+)) t) " +
	"ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC, POST_ID DESC)";
}   
