--------------------------------------------------------
--  파일이 생성됨 - 일요일-11월-29-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEST_WRITE
--------------------------------------------------------

  CREATE TABLE "SCOTT_B"."TEST_WRITE" 
   (	"WR_UID" NUMBER, 
	"WR_SUBJECT" VARCHAR2(200 BYTE), 
	"WR_CONTENT" CLOB, 
	"WR_NAME" VARCHAR2(40 BYTE), 
	"WR_VIEWCNT" NUMBER DEFAULT 0, 
	"WR_REGDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("WR_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into SCOTT_B.TEST_WRITE
SET DEFINE OFF;
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3434,'asdas','asdasd',2,to_date('20/11/26','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3428,'ㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇㅁ',1,to_date('20/11/25','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3443,'111111','ㄴㅇㄹㄴㅇ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3426,'홍단 홍단 대홍단 감자','asdas',3,to_date('20/11/25','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3440,'이게몬 개소리야','이게 몬 개소리야',3,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3431,'0','sadasd',0,to_date('20/11/26','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3433,'asdas','dasdasd',0,to_date('20/11/26','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3437,'ㄴㄴㄴ','1111',11,to_date('20/11/26','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3438,'ㅁㄴㅇㅁㄴㅇㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁㄴㅇㅁㄴ',3,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3439,'124124','21341245',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3441,'ㄴㅇㄴㅁㅇ','정민아 잘듣고 있누? ',9,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3479,'23ㄱ','3ㄱ',2,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3461,'ㅁㄴㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3462,'ㅁㄴㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3463,'ㄴㅁㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3464,'ㄴㅁㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3465,'ㅇㅁㄴㅇㅁ','ㅁㄴㅇㅁㄴ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3466,'ㅇㅁㄴㅇㅁ','ㅁㄴㅇㅁㄴ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3467,'ㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁㄴ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3468,'ㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁㄴ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3469,'ㅁㄴㅇ','ㄴㅁㅇ',24,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3470,'ㅁㄴㅇ','ㄴㅁㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3471,'ㅁㄴㅇ','ㅁㄴㅇㅁ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3472,'ㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁ',6,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3473,'ㅇㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁㄴ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3474,'ㅇㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁㄴ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3475,'ㅁㄴㅇ','ㅁㄴㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3476,'ㅁㄴㅇ','ㅁㄴㅇ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3477,'ㄱ32ㄱ3','32ㄱㄹ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3478,'ㄱ32ㄱ3','32ㄱㄹ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3480,'23ㄱ','3ㄱ',0,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3481,'ㅁ','ㅁ',1,to_date('20/11/27','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3502,'gvjhh','gjh',1,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3503,'asd','asd',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3504,'generatedkey test','generatedkey test',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3505,'asdas','asdas',1,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3506,'dasdasds','asdasda',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3507,'dasdasds','asdasda',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3508,'214213','213213',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3509,'214213','213213',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3510,'214213','213213',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3511,'214213','213213',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3512,'214213','213213',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3513,'^M^','^M^',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3514,'^M^','^M^',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3515,'ㅁㄴㅇㅁㄴㅇㅁ','ㅁㄴㅇㅁㄴㅇ',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3516,'ㅁㄴㅇㅁㄴㅇㅁ','ㅁㄴㅇㅁㄴㅇ',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3517,'ㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁ',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3518,'ㅁㄴㅇㅁㄴ','ㅁㄴㅇㅁ',0,to_date('20/11/28','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3519,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3520,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3521,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3522,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3523,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3524,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3525,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3526,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
Insert into SCOTT_B.TEST_WRITE (WR_UID,WR_SUBJECT,WR_NAME,WR_VIEWCNT,WR_REGDATE) values (3527,'asd','asd',0,to_date('20/11/29','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007757
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT_B"."SYS_C007757" ON "SCOTT_B"."TEST_WRITE" ("WR_UID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TEST_WRITE
--------------------------------------------------------

  ALTER TABLE "SCOTT_B"."TEST_WRITE" ADD PRIMARY KEY ("WR_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCOTT_B"."TEST_WRITE" MODIFY ("WR_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT_B"."TEST_WRITE" MODIFY ("WR_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT_B"."TEST_WRITE" MODIFY ("WR_UID" NOT NULL ENABLE);
