package main.java.com.model.board;

public class BoardList {
	// 카테고리 게시판
	public final static String SELECT_POST_BY_CATEGORY_ALL = "SELECT * FROM " + "(SELECT * FROM "
			+ "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE WHERE CATEGORY = ?), "
			+ "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE WHERE CATEGORY = ?)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+)) t) "
			+ "ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC, POST_ID DESC)";
	
	public final static String SELECT_POST_BY_CATEGORY_PAGE = "SELECT * FROM " + "(SELECT ROWNUM AS NO, t.* FROM "
			+ "(SELECT * FROM " + "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE WHERE CATEGORY = ?), "
			+ "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE WHERE CATEGORY = ?)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+)) t) "
			+ "ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC, POST_ID DESC) t) "
			+ "WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ " JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND NICKNAME LIKE ?"
			+ "	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";

	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ " JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ " JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND NICKNAME LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ " JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND TITLE LIKE ?"
			+ "	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ " JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ " JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";

	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_DATE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ?"
			+ "	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";

	public final static String SELECT_POST_BY_CATEGORY_SEARCH_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ?"
			+ "	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";

	public final static String SELECT_POST_BY_CATEGORY_SEARCH_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_CATEGORY_SEARCH_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ?"
			+ "	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	// 조회수 게시판
	public final static String SELECT_POST_BY_VIEWCNT_ALL = "SELECT * FROM " + "(SELECT * FROM "
			+ "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE), " + "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+) AND GRADE NOT IN('admin')) t) "
			+ "ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC, POST_ID DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_PAGE = "SELECT * FROM " + "(SELECT ROWNUM AS NO, t.* FROM "
			+ "(SELECT * FROM " + "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE), " + "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+) AND GRADE NOT IN('admin')) t) "
			+ "ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC, POST_ID DESC) t) "
			+ "WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND NICKNAME LIKE ?"
			+ " ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND NICKNAME LIKE ?"
			+ "	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";

	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND TITLE LIKE ?"
			+ " ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND TITLE LIKE ?"
			+ "	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin')"
			+ " ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_DATE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ? AND GRADE NOT IN('admin')"
			+ " ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";

	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ? AND GRADE NOT IN('admin')"
			+ " ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_VIEWCNT_SEARCH_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	// 공감 게시판
	
	public final static String SELECT_POST_BY_EMPATHIZE_ALL = "SELECT * FROM " + "(SELECT * FROM "
			+ "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE), " + "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+) AND GRADE NOT IN('admin')) t) "
			+ "ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC, POST_ID DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_PAGE = "SELECT * FROM " + "(SELECT ROWNUM AS NO, t.* FROM "
			+ "(SELECT * FROM " + "(SELECT t.*, NVL(t.HIT, 0) AS EMPATHIZE_CNT FROM " + "(SELECT t1.*, t2.HIT FROM "
			+ "(SELECT t1.*, t2.FILE_ID, t2.FILEKIND, t2.REAL_FILENAME, t2.FILENAME FROM " + "(SELECT * FROM "
			+ "(SELECT *  FROM (SELECT * FROM POST_TABLE), " + "(SELECT COUNT(*) AS DATALENGTH FROM POST_TABLE)) t1, "
			+ "MM_TABLE t2 WHERE t1.WRITER = t2.MM_ID) t1, " + "FILE_TABLE t2 WHERE t1.POST_CONTENTS = t2.FILE_ID) t1, "
			+ "(SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) t2 "
			+ "WHERE t1.POST_ID = t2.POST_ID(+) AND GRADE NOT IN('admin')) t) "
			+ "ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC, POST_ID DESC) t) "
			+ "WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_EMPATHIZET_SEARCH_DATE_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND NICKNAME LIKE ?"
			+ " ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_DATE_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND NICKNAME LIKE ?"
			+ "	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_EMPATHIZET_SEARCH_DATE_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND TITLE LIKE ?"
			+ " ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_DATE_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin') AND TITLE LIKE ?"
			+ "	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_DATE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin')"
			+ " ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_DATE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE T >= ? AND T <= ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_WRITER_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ? AND GRADE NOT IN('admin')"
			+ " ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_WRITER_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE NICKNAME LIKE ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ? AND GRADE NOT IN('admin')"
			+ " ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC)";
	
	public final static String SELECT_POST_BY_EMPATHIZE_SEARCH_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ "	WHERE TITLE LIKE ? AND GRADE NOT IN('admin')"
			+ "	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";

	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	// 내가 쓴글
	public final static String SELECT_POST_BY_MYPAGE_ALL = "SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ " JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ " JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC";
	
	public final static String SELECT_POST_BY_MYPAGE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ " (SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ "	WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_DATE_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_DATE_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ? AND TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_DATE_ALL = "SELECT * FROM" 
		    + " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_DATE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE T >= ? AND T <= ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_TITLE_ALL = "SELECT * FROM" 
			+ " (SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ "	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC)";
	
	public final static String SELECT_POST_BY_MYPAGE_SEARCH_TITLE_PAGE = "SELECT * FROM"
			+ " (SELECT ROWNUM AS NO, t.* FROM" 
			+ "	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM"
			+ "	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YY-MM-DD'), 'YY-MM-DD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = ?) p"
			+ "	JOIN MM_TABLE m ON p.WRITER = m.MM_ID"
			+ "	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID"
			+ " LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID"
			+ " WHERE TITLE LIKE ?"
			+ " ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)"
			+ " WHERE NO >= ? AND NO <= ?";
	
	
}
