select * from dba_tablespaces;

SELECT FILE_NAME, FILE_ID, TABLESPACE_NAME, STATUS
FROM DBA_DATA_FILES
WHERE TABLESPACE_NAME = 'TP_2';
 
-- C:\ORACLEXE\APP\ORACLE\ORADATA\KOREA\TP_BBB.DBF	5	TP_2	AVAILABLE



ALTER DATABASE DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\KOREA\TP_BBB.DBF' RESIZE 100000000;